/* ble_adv.cpp - see ble_adv.h. */
#include "ble_adv.h"

#include "ble_stack.h"
#include "wifi.h"

#include <Arduino.h>
#include <NimBLEDevice.h>
/* ble_hs_id_gen_rnd / ble_hs_id_set_rnd, for #89's MAC rotation. Reached the
 * same two ways NimBLE-Arduino reaches its own host headers (see NimBLEUtils.h):
 * the IDF's own NimBLE component when CONFIG_NIMBLE_CPP_IDF is set, otherwise
 * the copy this library bundles. */
#if defined(CONFIG_NIMBLE_CPP_IDF)
#include "host/ble_hs.h"
#else
#include "nimble/nimble/host/include/host/ble_hs.h"
#endif

#include <cstring>
#include <string>

namespace {

/* The whole of an advertisement is 31 bytes. A payload longer than that is one
 * the app built wrong - ble_gap_adv_set_data would reject it - so it is turned
 * away here rather than passed down to fail as a return code nothing reads. */
const size_t kMaxPayload = 31;

/* The controller counts advertising intervals in 0.625 ms steps. A caller asks
 * in milliseconds because that is the unit a person sets a beacon in; this is
 * where the two meet. */
uint16_t ms_to_units(uint32_t ms)
{
    uint32_t units = (ms * 8) / 5;      /* ms / 0.625 */
    if (units < 0x20) units = 0x20;     /* the spec's floor, 20 ms */
    if (units > 0x4000) units = 0x4000; /* and ceiling, ~10.24 s */
    return (uint16_t)units;
}

bool g_up;

/* How the next begin is shaped (#89). All default to #60's beacon: a
 * non-connectable advertisement, no scan response, the controller's own
 * address. set_type / set_addr change them; begin reads and applies them. */
bool g_connectable;
std::string g_scan_rsp;
bool g_addr_pending;
bool g_addr_random;
uint8_t g_addr[6];

/* Put the chosen address on the controller, if one was asked for since the last
 * begin. A random static address is generated by the host (ble_hs_id_gen_rnd
 * sets the two top bits the spec requires); an explicit six bytes are trusted
 * as given. Either way the own-address type becomes random so advertising uses
 * it. Called after reset() and before start(), when the radio is not mid-air -
 * ble_hs_id_set_rnd will not change the address of a running advertisement. */
void apply_addr()
{
    if (!g_addr_pending) return;
    ble_addr_t a;
    if (g_addr_random) {
        ble_hs_id_gen_rnd(0, &a);
    } else {
        a.type = BLE_ADDR_RANDOM;
        memcpy(a.val, g_addr, 6);
    }
    ble_hs_id_set_rnd(a.val);
    NimBLEDevice::setOwnAddrType(BLE_OWN_ADDR_RANDOM);
    g_addr_pending = false;
}

} /* namespace */

void catnip_ble_adv_set_type(bool connectable, const uint8_t *scan_rsp,
                             size_t scan_rsp_len)
{
    g_connectable = connectable;
    if (scan_rsp && scan_rsp_len > 0)
        g_scan_rsp.assign(reinterpret_cast<const char *>(scan_rsp), scan_rsp_len);
    else g_scan_rsp.clear();
}

void catnip_ble_adv_set_addr(const uint8_t *addr)
{
    if (addr) {
        memcpy(g_addr, addr, 6);
        g_addr_random = false;
    } else {
        g_addr_random = true;
    }
    g_addr_pending = true;
}

bool catnip_ble_adv_begin(const uint8_t *payload, size_t len, uint32_t interval_ms)
{
    if (!payload || len == 0 || len > kMaxPayload) return false;

    /* A re-arm is not a second user of the stack. begin() doubles as the app's
     * "change the id" call, so the stack is acquired and the Wi-Fi held on the
     * first begin only - acquiring again on every change would run the refcount
     * up past the one end() that will ever release it, and the stack would never
     * come down. */
    bool was_up = g_up;
    if (!was_up && !catnip_ble_stack_acquire()) return false;

    NimBLEAdvertising *adv = NimBLEDevice::getAdvertising();
    /* Re-arm from a clean slate. begin() doubles as the app's "change the id"
     * call, so a second one lands on an advertising object the first left
     * configured - and reset() is what stops the old payload's fields from
     * surviving under the new raw data. It also stops any advertising in
     * flight, which is what makes re-arming a replacement rather than a race. */
    adv->reset();

    /* The adv type and scan response, as #89 last asked - defaulting to #60's
     * ADV_NONCONN_IND with the scan response off, which keeps the air quiet and
     * leaves all 31 bytes to the payload. A connectable ADV_IND is what makes a
     * phone offer to pair; a scan response is a second packet answered on ask. */
    adv->setAdvertisementType(g_connectable ? BLE_GAP_CONN_MODE_UND
                                            : BLE_GAP_CONN_MODE_NON);
    if (!g_scan_rsp.empty()) {
        NimBLEAdvertisementData sr;
        sr.addData(g_scan_rsp);
        adv->setScanResponseData(sr);
        adv->setScanResponse(true);
    } else {
        adv->setScanResponse(false);
    }

    /* The advertiser address #89 last asked for, if any - a fresh random one per
     * cycle is how the catalogue looks like many devices. After reset() so the
     * radio is down while it changes. */
    apply_addr();

    uint16_t units = ms_to_units(interval_ms);
    adv->setMinInterval(units);
    adv->setMaxInterval(units);

    /* The payload verbatim. setAdvertisementData hands these bytes straight to
     * the controller and marks the data custom, so start() adds nothing of its
     * own - no flags, no name - which is the whole point of assembling the AD
     * structures in the app: what goes on the air is exactly what was built.
     * addData copies into the object's own storage, so `payload` need not
     * outlive this call. */
    NimBLEAdvertisementData data;
    data.addData(std::string(reinterpret_cast<const char *>(payload), len));
    adv->setAdvertisementData(data);

    if (!adv->start()) {
        if (was_up) {
            /* A failed re-arm is not the old beacon carrying on. reset() above
             * already stopped it, so nothing is on the air - and leaving g_up
             * true would hold the stack and the Wi-Fi for a beacon that is gone
             * and make state() claim it is advertising. Drop to a truthful off.
             * This is the case #89's rapid cycling makes reachable. */
            catnip_ble_adv_end();
        } else {
            /* Nothing was up and nothing started: give back only what this call
             * took, the acquire above. */
            catnip_ble_stack_release();
        }
        return false;
    }

    /* The promise from the header: while this is a beacon, the front end is this
     * radio's. Held on the first begin only, alongside the acquire. */
    if (!was_up) catnip_wifi_hold(true);
    g_up = true;

    Serial.printf("[catnip] ble-adv: advertising %u bytes every %u ms\n", (unsigned)len,
                  (unsigned)interval_ms);
    return true;
}

void catnip_ble_adv_end(void)
{
    if (!g_up) return;
    g_up = false;

    NimBLEDevice::stopAdvertising();

    /* The surface goes down to its #60 default, so the next app that raises it -
     * beacon or spam - starts non-connectable, silent, and on the controller's
     * own public address rather than inheriting the last cycle's spoof shape.
     * Reverting the own-address type is the part that actually gives the address
     * back: a spam cycle left NimBLE on a random-static address it set with
     * ble_hs_id_set_rnd, and clearing g_addr_pending alone would leave that type
     * in force for the next begin - so a following #60 beacon would advertise
     * under a leftover random MAC. Setting it back to public is what makes the
     * "own address" this comment promises true. */
    g_connectable = false;
    g_scan_rsp.clear();
    g_addr_pending = false;
    NimBLEDevice::setOwnAddrType(BLE_OWN_ADDR_PUBLIC);

    catnip_ble_stack_release();
    catnip_wifi_hold(false);
    Serial.println("[catnip] ble-adv: beacon down");
}

bool catnip_ble_adv_up(void)
{
    return g_up;
}
