/*
 * catnip_font_display.h - the `display` style role's face (#74).
 *
 * Digits, a colon, a point and a minus, at a size that owns the panel. It is
 * generated by tools/gen_font.py out of the Montserrat-Medium.ttf inside the
 * pinned LVGL dependency - the same file LVGL's own built-in faces are cut
 * from - and the result is committed, the way the icons are, so that a build on
 * a bare runner needs neither a TTF nor a font renderer.
 *
 * There are no letters in it, and that is the rule rather than an economy: ask
 * for `display` with words in the string and you get missing-glyph boxes at the
 * size you asked for, which is the loudest way to be told that this role is for
 * a quantity and the five prose roles are for prose.
 */
#ifndef CATNIP_FONT_DISPLAY_H
#define CATNIP_FONT_DISPLAY_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t catnip_font_display;

#ifdef __cplusplus
}
#endif

#endif /* CATNIP_FONT_DISPLAY_H */
