/* Generated by tools/gen_icons.py - do not edit. */
#ifndef CATNIP_ICON_IMG_H
#define CATNIP_ICON_IMG_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t catnip_icon_img_14[12];
extern const lv_image_dsc_t catnip_icon_img_64[12];

#ifdef __cplusplus
}
#endif

#endif /* CATNIP_ICON_IMG_H */
