/* Generated by tools/gen_icons.py - do not edit. */
#include <lvgl.h>

#include "../catnip_icon_bits.h"
#include "catnip_icon_img.h"

/* clang-format off */
const lv_image_dsc_t catnip_icon_img_14[12] = {
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[0],
        .reserved = NULL,
    }, /* folder */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[1],
        .reserved = NULL,
    }, /* file */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[2],
        .reserved = NULL,
    }, /* placeholder */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[3],
        .reserved = NULL,
    }, /* image */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[4],
        .reserved = NULL,
    }, /* audio */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[5],
        .reserved = NULL,
    }, /* settings */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[6],
        .reserved = NULL,
    }, /* edit */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[7],
        .reserved = NULL,
    }, /* trash */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[8],
        .reserved = NULL,
    }, /* refresh */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[9],
        .reserved = NULL,
    }, /* warning */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[10],
        .reserved = NULL,
    }, /* ok */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 14,
            .h = 14,
            .stride = 28,
            .reserved_2 = 0,
        },
        .data_size = 588,
        .data = catnip_icon_rgb565a8_14[11],
        .reserved = NULL,
    }, /* close */
};

const lv_image_dsc_t catnip_icon_img_64[12] = {
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[0],
        .reserved = NULL,
    }, /* folder */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[1],
        .reserved = NULL,
    }, /* file */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[2],
        .reserved = NULL,
    }, /* placeholder */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[3],
        .reserved = NULL,
    }, /* image */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[4],
        .reserved = NULL,
    }, /* audio */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[5],
        .reserved = NULL,
    }, /* settings */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[6],
        .reserved = NULL,
    }, /* edit */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[7],
        .reserved = NULL,
    }, /* trash */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[8],
        .reserved = NULL,
    }, /* refresh */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[9],
        .reserved = NULL,
    }, /* warning */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[10],
        .reserved = NULL,
    }, /* ok */
    {
        .header = {
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565A8,
            .flags = 0,
            .w = 64,
            .h = 64,
            .stride = 128,
            .reserved_2 = 0,
        },
        .data_size = 12288,
        .data = catnip_icon_rgb565a8_64[11],
        .reserved = NULL,
    }, /* close */
};
/* clang-format on */
