"""Turn binary assets into C arrays at build time (PlatformIO pre-script).

The splash has to be in flash, not on the SD card: it is drawn before the card
is mounted and before any image decoder exists. Rather than commit a ~600 KB
generated header, the blob is converted here on the way into a build, so the
repository keeps the artwork and the build keeps the array.
"""
import os
import struct


# PlatformIO execs this through SCons, where __file__ does not exist but an
# `env` is injected; fall back to __file__ so the script still runs standalone.
try:
    Import("env")  # noqa: F821
    FIRMWARE = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    FIRMWARE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(FIRMWARE)
ASSETS = os.path.join(REPO, "docs", "assets", "meowkit")
OUT_DIR = os.path.join(FIRMWARE, "src", "generated")

W, H = 320, 240


def emit_rgb565(src, out, symbol):
    """Write `src` (raw little-endian RGB565) out as a uint16_t array."""
    with open(src, "rb") as f:
        blob = f.read()
    want = W * H * 2
    if len(blob) != want:
        raise SystemExit(
            "%s is %d bytes, expected %d (%dx%d RGB565)"
            % (src, len(blob), want, W, H)
        )
    # The file is little-endian, which is also the ESP32's native uint16_t
    # layout, so the values go through unchanged; the display driver deals with
    # whatever byte order the panel wants on the wire.
    px = struct.unpack("<%dH" % (W * H), blob)
    lines = []
    for i in range(0, len(px), 12):
        lines.append("    " + " ".join("0x%04X," % v for v in px[i:i + 12]))
    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_assets.py - do not edit. */\n")
        f.write("#ifndef CATNIP_GEN_%s_H\n" % symbol.upper())
        f.write("#define CATNIP_GEN_%s_H\n\n" % symbol.upper())
        f.write("#include <stdint.h>\n\n")
        f.write("#define %s_W %d\n#define %s_H %d\n\n" % (symbol.upper(), W, symbol.upper(), H))
        f.write("static const uint16_t %s[%d] = {\n" % (symbol, W * H))
        f.write("\n".join(lines))
        f.write("\n};\n\n#endif\n")


def build():
    os.makedirs(OUT_DIR, exist_ok=True)
    src = os.path.join(ASSETS, "catnip_splash_320x240.rgb565")
    out = os.path.join(OUT_DIR, "splash_rgb565.h")
    if not os.path.exists(src):
        raise SystemExit("missing asset: %s" % src)
    if os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(src):
        return  # up to date
    emit_rgb565(src, out, "catnip_splash")
    print("gen_assets: wrote %s" % os.path.relpath(out, REPO))


build()
