"""Embed firmware/apps/* into the image at build time (PlatformIO pre-script).

A built-in app is the same thing as an app on the card - the same manifest, the
same main.lua, the same icon - and it is loaded through the same code. What it
cannot do is live on the card, because the card is removable and the File
Browser is how you look at one. So the files are compiled in.

Generated rather than committed, for the reason gen_assets.py gives: the source
of truth is the app directory, and a checked-in copy of it would be a second
one. src/generated/ is ignored.
"""
import json
import os

try:
    Import("env")  # noqa: F821
    FIRMWARE = env["PROJECT_DIR"]  # noqa: F821
    # CATNIP_BUILTIN_APPS is set in platformio.ini rather than here: a define a
    # build script appends is one nobody reading the build config can see.
except NameError:
    FIRMWARE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

APPS_DIR = os.path.join(FIRMWARE, "apps")
OUT_DIR = os.path.join(FIRMWARE, "src", "generated")
OUT = os.path.join(OUT_DIR, "builtin_apps.h")


def c_string(text):
    """A C string literal, split a line at a time so the result stays readable
    and no compiler's string-length limit is anywhere near."""
    out = []
    for line in text.split("\n"):
        esc = (
            line.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\t", "\\t")
            .replace("\r", "")
        )
        out.append('    "%s\\n"' % esc)
    return "\n".join(out) if out else '    ""'


def c_bytes(blob):
    rows = []
    for i in range(0, len(blob), 16):
        rows.append("    " + " ".join("0x%02X," % b for b in blob[i : i + 16]))
    return "\n".join(rows)


def discover():
    if not os.path.isdir(APPS_DIR):
        return []
    apps = []
    for name in sorted(os.listdir(APPS_DIR)):
        d = os.path.join(APPS_DIR, name)
        man = os.path.join(d, "manifest.json")
        lua = os.path.join(d, "main.lua")
        if not (os.path.isdir(d) and os.path.isfile(man) and os.path.isfile(lua)):
            continue
        with open(man, encoding="utf-8") as f:
            raw = f.read()
        m = json.loads(raw)
        icon_name = m.get("icon", "")
        icon = b""
        if icon_name:
            p = os.path.join(d, icon_name)
            if os.path.isfile(p):
                with open(p, "rb") as f:
                    icon = f.read()
        with open(lua, encoding="utf-8") as f:
            apps.append(
                {
                    "dir": name,
                    "id": m.get("id", name),
                    "name": m.get("name", name),
                    "icon_name": icon_name,
                    "manifest": raw,
                    "lua": f.read(),
                    "icon": icon,
                }
            )
    return apps


def emit(apps):
    lines = [
        "/* Generated by tools/gen_apps.py - do not edit. */",
        "#ifndef CATNIP_GEN_BUILTIN_APPS_H",
        "#define CATNIP_GEN_BUILTIN_APPS_H",
        "",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char *id;",
        "    const char *name;",
        "    const char *icon_name;    /* as the manifest spells it, or \"\" */",
        "    const char *manifest;",
        "    const char *lua;",
        "    const unsigned char *icon; /* the icon file's own bytes, or NULL */",
        "    size_t icon_len;",
        "} catnip_builtin_app;",
        "",
    ]
    for i, a in enumerate(apps):
        if a["icon"]:
            lines.append("static const unsigned char builtin_icon_%d[] = {" % i)
            lines.append(c_bytes(a["icon"]))
            lines.append("};")
            lines.append("")
        lines.append("static const char builtin_manifest_%d[] =" % i)
        lines.append(c_string(a["manifest"]) + ";")
        lines.append("")
        lines.append("static const char builtin_lua_%d[] =" % i)
        lines.append(c_string(a["lua"]) + ";")
        lines.append("")

    lines.append("static const catnip_builtin_app catnip_builtin_apps[] = {")
    for i, a in enumerate(apps):
        lines.append("    {")
        lines.append('        .id = "%s",' % a["id"])
        lines.append('        .name = "%s",' % a["name"])
        lines.append('        .icon_name = "%s",' % a["icon_name"])
        lines.append("        .manifest = builtin_manifest_%d," % i)
        lines.append("        .lua = builtin_lua_%d," % i)
        if a["icon"]:
            lines.append("        .icon = builtin_icon_%d," % i)
            lines.append("        .icon_len = sizeof(builtin_icon_%d)," % i)
        else:
            lines.append("        .icon = NULL,")
            lines.append("        .icon_len = 0,")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#define CATNIP_BUILTIN_APP_COUNT %d" % len(apps))
    lines.append("")
    lines.append("#endif /* CATNIP_GEN_BUILTIN_APPS_H */")
    lines.append("")
    return "\n".join(lines)


def main():
    apps = discover()
    os.makedirs(OUT_DIR, exist_ok=True)
    text = emit(apps)
    old = None
    if os.path.isfile(OUT):
        with open(OUT, encoding="utf-8") as f:
            old = f.read()
    if old != text:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
    print(
        "gen_apps: %d built-in app(s): %s"
        % (len(apps), ", ".join(a["id"] for a in apps) or "-")
    )


main()
