"""Turn binary assets into C arrays at build time (PlatformIO pre-script).

The splash and the idle-animation frames have to be in flash, not on the SD
card: they are drawn before the card is mounted and before any image decoder
exists. Rather than commit ~600 KB of generated header per frame, each blob
(made by tools/png_to_rgb565.py and committed next to the artwork) is converted
here on the way into a build, so the repository keeps the artwork and the build
keeps the arrays.
"""
import os
import struct


# PlatformIO execs this through SCons, where __file__ does not exist but an
# `env` is injected; fall back to __file__ so the script still runs standalone.
try:
    Import("env")  # noqa: F821
    FIRMWARE = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    FIRMWARE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(FIRMWARE)
ASSETS = os.path.join(REPO, "docs", "assets", "meowkit")
OUT_DIR = os.path.join(FIRMWARE, "src", "generated")

W, H = 320, 240


def emit_rgb565(src, out, symbol):
    """Write `src` (raw little-endian RGB565) out as a uint16_t array."""
    with open(src, "rb") as f:
        blob = f.read()
    want = W * H * 2
    if len(blob) != want:
        raise SystemExit(
            "%s is %d bytes, expected %d (%dx%d RGB565)"
            % (src, len(blob), want, W, H)
        )
    # The file is little-endian, which is also the ESP32's native uint16_t
    # layout, so the values go through unchanged; the display driver deals with
    # whatever byte order the panel wants on the wire.
    px = struct.unpack("<%dH" % (W * H), blob)
    lines = []
    for i in range(0, len(px), 12):
        lines.append("    " + " ".join("0x%04X," % v for v in px[i:i + 12]))
    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_assets.py - do not edit. */\n")
        f.write("#ifndef CATNIP_GEN_%s_H\n" % symbol.upper())
        f.write("#define CATNIP_GEN_%s_H\n\n" % symbol.upper())
        f.write("#include <stdint.h>\n\n")
        f.write("#define %s_W %d\n#define %s_H %d\n\n" % (symbol.upper(), W, symbol.upper(), H))
        f.write("static const uint16_t %s[%d] = {\n" % (symbol, W * H))
        f.write("\n".join(lines))
        f.write("\n};\n\n#endif\n")


# (asset blob, generated header, C symbol). The splash doubles as frame 0 of
# the idle animation: the waving paw up at rest, no motion arcs. Frame 1 tips
# the paw out with one short arc above it. Frame 2 is the full sweep, with arcs
# off both the paw and the tail. The firmware plays 0, 1, 2, 1.
BLOBS = [
    ("catnip_splash_320x240.rgb565", "splash_rgb565.h", "catnip_splash"),
    ("catnip_anim_f01_320x240.rgb565", "anim_f01_rgb565.h", "catnip_anim_f01"),
    ("catnip_anim_f02_320x240.rgb565", "anim_f02_rgb565.h", "catnip_anim_f02"),
]


def drop_stale_headers():
    """A leftover anim_f03_rgb565.h from an earlier 12-frame wave would still
    compile if anything included it. Only the three current headers stay."""
    keep = set(header for _, header, _ in BLOBS)
    if not os.path.isdir(OUT_DIR):
        return
    for name in os.listdir(OUT_DIR):
        if name.endswith(".h") and name not in keep:
            os.remove(os.path.join(OUT_DIR, name))
            print("gen_assets: removed leftover %s" % name)


def build():
    os.makedirs(OUT_DIR, exist_ok=True)
    drop_stale_headers()
    for blob, header, symbol in BLOBS:
        src = os.path.join(ASSETS, blob)
        out = os.path.join(OUT_DIR, header)
        if not os.path.exists(src):
            raise SystemExit("missing asset: %s" % src)
        if os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(src):
            continue  # up to date
        emit_rgb565(src, out, symbol)
        print("gen_assets: wrote %s" % os.path.relpath(out, REPO))


build()
