"""Write the build's own version into the image (PlatformIO pre-script).

Nothing in this repo carried a version, so a device could not say what it was
running and a bug report could not say which build it came from. This is that
string, taken from git rather than kept in a file: a number somebody has to
remember to bump is a number that is wrong most of the time, and the tag plus
the commit is already the truth.

A build with no git - a tarball, a fresh clone of a shallow mirror, a machine
without the binary - gets "dev" and builds anyway. The version exists to tell
builds apart; refusing to produce one would be the tail wagging the dog.

Generated rather than committed, for the reason gen_apps.py gives: the source of
truth is the repository, and a checked-in copy of it would be a second one.
src/generated/ is ignored.
"""
import datetime
import os
import subprocess

try:
    Import("env")  # noqa: F821
    FIRMWARE = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    FIRMWARE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

OUT_DIR = os.path.join(FIRMWARE, "src", "generated")
OUT = os.path.join(OUT_DIR, "version.h")

FALLBACK = "dev"


def describe():
    """The tag, the commits since it, the short hash, and whether the tree is
    dirty - e.g. `v0.3.1-4-g44e71ad-dirty`. Falls back to the bare hash before
    the first tag, and to FALLBACK when git cannot answer at all."""
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=FIRMWARE,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return FALLBACK
    if out.returncode != 0:
        return FALLBACK
    return out.stdout.strip() or FALLBACK


def main():
    version = describe()
    # The date and not the time: a version already identifies the build, and a
    # timestamp would make every rebuild of the same commit produce a different
    # header and relink the world.
    built = datetime.date.today().isoformat()

    text = (
        "/* Generated by tools/gen_version.py - do not edit, and do not commit. */\n"
        "#ifndef CATNIP_GENERATED_VERSION_H\n"
        "#define CATNIP_GENERATED_VERSION_H\n"
        "\n"
        '#define CATNIP_VERSION "%s"\n'
        '#define CATNIP_BUILD_DATE "%s"\n'
        "\n"
        "#endif /* CATNIP_GENERATED_VERSION_H */\n"
    ) % (version, built)

    os.makedirs(OUT_DIR, exist_ok=True)
    # Only when it differs, so an unchanged version does not touch the file and
    # rebuild everything that includes it.
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as f:
            if f.read() == text:
                print("gen_version: %s (unchanged)" % version)
                return
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("gen_version: %s" % version)


main()
